version = 0.1
[default.deploy.parameters]
stack_name = "date-knight-waitlist"
resolve_s3 = true
s3_prefix = "date-knight-waitlist"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
